#
# Custom Makefile targets
#

uvdensitometer-desc.dat: uvdensitometer.bin
	$(PERL) ../../tools/checksum.pl uvdensitometer.bin uvdensitometer-desc.dat

uvdensitometer-out.elf: uvdensitometer.elf uvdensitometer-desc.dat
	arm-none-eabi-objcopy --update-section .app_descriptor=uvdensitometer-desc.dat \
	  uvdensitometer.elf uvdensitometer-out.elf

uvdensitometer-out.bin: uvdensitometer-out.elf
	arm-none-eabi-objcopy -O binary uvdensitometer-out.elf "uvdensitometer-out.bin"

uvdensitometer.dfu : uvdensitometer-out.bin
	$(PYTHON) ../../tools/dfuse-pack.py -b 0x08008000:uvdensitometer-out.bin -D 0x0483:0xdf11 -a 0 uvdensitometer.dfu

uvdensitometer.uf2 : uvdensitometer-out.bin
	$(PYTHON) ../../tools/uf2conv.py -f 0x202E3A91 -b 0x08008000 -c -o uvdensitometer.uf2 uvdensitometer-out.bin
